language: python

services:
  - docker

before_install:
  - pip install tavern==0.34.0

script:
- cd tests && make apitest webapptest

jobs:
  include:
    - stage: "api"                # naming the Tests stage
      name: "Testing Hub API"            # names the first Tests stage job
      script: cd tests && make apitest
    - stage: "webapp"
      name: "Testing webapp UI (tutorial)"
      script: cd tests && make test_webapp_tutorial
    - stage: "studio4mygene"
      script: cd tests && make test_studio4mygene

cache:
  directories:
    - tests/webapp/tutorial/node_modules/node_modules
    - tests/webapp/studio4mygene/node_modules
