#!/bin/bash
source ~/pyenv/bin/activate
cd ~/{{ api_name }}/src
tmux kill-session -t hub 2> /dev/null
tmux new-session -d -s hub 
tmux send-keys 'python ~/{{ app_name}}/bin/hub.py' C-m
tmux detach -s hub
