#!/bin/bash
source ~/pyenv/bin/activate
cd ~/{{ app_name }}
tmux kill-session -t hub 2> /dev/null
tmux new-session -d -s hub
tmux send-keys 'python bin/hub.py' C-m
# not needed with tmux 2.6 ? if left, gives "no current client"
#tmux detach -s hub
