---

app_name: "biothings_studio"

# Variables relating to the whole cluster
cluster:
  name: biothings
  environment: studio

software:
  web_node:
    elasticsearch:
      plugin:
        head: "mobz/elasticsearch-head"
        bigdesk: "lukas-vlcek/bigdesk"
      heap_size: "2g"
      elasticsearch_yml:
        - "node.data: true"
        - "node.master: true"
    studio_repository: "https://github.com/biothings/{{ app_name }}.git" 
    studio_git_version: "{{ studio_version | default('master')}}"
    biothings_git_version: "{{ biothings_version | default('master')}}"
  common_configurations:
    elasticsearch:
      soft_file_limit: "32000"
      hard_file_limit: "65535"
      elasticsearch_yml:
        - "network.host: 0.0.0.0"
    mongodb:
      port: 27017
      bindip: "127.0.0.1"
      oplogsizemb: 50
      dbpath: "/data/mongodb"
      logpath: "/data/logs/mongodb"
      replsetname: "monitor"
