services:
  mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.13
    environment:
      - discovery.type=single-node
    ulimits: 
      nofile:
        soft: 32000
        hard: 65535
    ports:
      - "9200:9200"
  webapp:
    build: ./webapp
    ports:
      - "8080:8080"
  biothings:
    build:
      context: ./biothings
      args:
        # Temporary workaround
        BIOTHINGS_GIT: https://github.com/zcqian/biothings.api.git
